USE codeup_test_db;

DROP TABLE IF EXISTS albums;

CREATE TABLE albums (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  artist VARCHAR(100) DEFAULT 'NONE',
  name VARCHAR(100) DEFAULT NULL,
  release_date INT UNSIGNED DEFAULT NULL,
  sales FLOAT UNSIGNED DEFAULT NULL,
  genre VARCHAR (25) DEFAULT NULL,
  PRIMARY KEY (id)
);